export const GET_STATE_DATA = 'GET_STATE_DATA';
export const STATE_ERROR = 'STATE_ERROR';
export const SET_CURRENT_STATE = 'SET_CURRENT_STATE';
export const CLEAR_CURRENT_STATE = 'CLEAR_CURRENT_STATE';
