export const GET_STATE_DATA = 'GET_STATE_DATA';
export const STATE_ERROR = 'STATE_ERROR';
export const SET_CURRENT_STATE = 'SET_CURRENT_STATE';
export const CLEAR_CURRENT_STATE = 'CLEAR_CURRENT_STATE';
export const FILTER_STATE = 'FILTER_STATE';
export const CLEAR_FILTER = 'CLEAR_FILTER';

export const GET_COUNTRY_DATA = 'GET_COUNTRY_DATA';
export const COUNTRY_ERROR = 'COUNTRY_ERROR';
export const SET_CURRENT_COUNTRY = 'SET_CURRENT_COUNTRY';
export const FILTER_COUNTRY = 'FITLER_COUNTRY';

export const GET_NEWS = 'GET_NEWS';
export const NEWS_ERROR = 'NEWS_ERROR';
